name: "Docker API CalVer Action"
description: "Compute CalVer Tags for a given Docker Repository. Uses Docker HTTP API V2 (https://distribution.github.io/distribution/spec/api/)."
author: itsteddyyo
branding:
    icon: calendar
    color: blue
inputs:
    repository:
        description: "Full repository path including host, namespace, image, e.g. ghcr.io/myorg/myimage (host/repo_path)"
        required: true
    registry_scheme:
        description: "Scheme to use for registry requests: http or https (default: https)"
        required: false
        default: "https"
    auth_mode:
        description: "Authentication mode: noauth, basic, bearer (default: none)"
        required: false
        default: "none"
    registry_username:
        description: "Username for basic auth (required if auth_mode=basic)"
        required: false
    registry_password:
        description: "Password for basic auth (required if auth_mode=basic). Token for bearer auth (required if auth_mode=bearer)."
        required: false
    calver_format:
        description:
            "CalVer format to use. See https://www.npmjs.com/package/@lets-release/calver and
            https://github.com/lets-release/lets-release/blob/main/libs/calver/src/__fixtures__/formats.ts"
        required: false
        default: "YYYY.MM.MICRO"
outputs:
    current:
        description: "The current newest CalVer tag found in the registry"
    new:
        description: "The new CalVer tag computed by this action"
runs:
    using: node24
    main: dist/index.js
